#!/usr/bin/env bash

# Script must be executed as root because of package installations
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo Update submodules
git submodule update --init --recursive

echo
echo Install zsh
apt-get install zsh
chsh -s $(which zsh)

echo
echo Install oh-my-zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo
echo "Install nvm (Node Version Manager)"
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

echo
echo Install nodejs
nvm use node

echo
echo Install diff-so-fancy
npm i -g diff-so-fancy
