#!/usr/bin/env bash

# Script must be executed as root because of package installations
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo Update submodules
git submodule update --init --recursive

echo Install zsh
apt-get install zsh
chsh -s $(which zsh)

echo Install oh-my-zsh
sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
